name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: free up disk
        run: ./free_disk_space.sh
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: votiethuy/dreambooth-lora
          tags: |
            type=sha
            type=sha,format=long
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
